-- MySQL Script generated by MySQL Workbench
-- Sun Nov 13 08:47:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TOOLSRENTAL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TOOLSRENTAL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TOOLSRENTAL` DEFAULT CHARACTER SET utf8 ;
USE `TOOLSRENTAL` ;

-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`Ciudad` (
  `idCiudad` INT NOT NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`Comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`Comuna` (
  `idComuna` INT NOT NULL,
  `comuna` VARCHAR(45) NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idComuna`, `Ciudad_idCiudad`),
  INDEX `fk_Comuna_Ciudad1_idx` (`Ciudad_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_Comuna_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `TOOLSRENTAL`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`Clientes` (
  `idCliente` INT NOT NULL,
  `nomCliente` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `altura` VARCHAR(45) NULL,
  `Comuna_idComuna` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Clientes_Comuna1_idx` (`Comuna_idComuna` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Comuna1`
    FOREIGN KEY (`Comuna_idComuna`)
    REFERENCES `TOOLSRENTAL`.`Comuna` (`idComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`Pedidos` (
  `idPedido` INT NOT NULL,
  `idCliente` VARCHAR(45) NULL,
  `fechaPedido` DATE NULL,
  `Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Clientes_idCliente`),
  INDEX `fk_Pedidos_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `TOOLSRENTAL`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`DetallePedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`DetallePedidos` (
  `idDetPed` INT NOT NULL,
  `cantProd` INT NULL,
  `precio` DECIMAL(2) NULL,
  `subTotal` DECIMAL(2) NULL,
  `Pedidos_idPedido` INT NOT NULL,
  `DetallePedidoscol` VARCHAR(45) NULL,
  `Pedidos_Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idDetPed`, `Pedidos_idPedido`, `Pedidos_Clientes_idCliente`),
  INDEX `fk_Orden_Pedidos1_idx` (`Pedidos_idPedido` ASC, `Pedidos_Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Orden_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedido` , `Pedidos_Clientes_idCliente`)
    REFERENCES `TOOLSRENTAL`.`Pedidos` (`idPedido` , `Clientes_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`Categorias` (
  `idCategoria` INT NOT NULL,
  `nomCategoria` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`GuiasRemision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`GuiasRemision` (
  `idGuiaRemision` INT NOT NULL,
  `cantProducto` INT NULL,
  `itemsDespachados` INT NULL,
  `fechaSalida` DATE NULL,
  PRIMARY KEY (`idGuiaRemision`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`DetalleGuias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`DetalleGuias` (
  `idDetalleGuia` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `GuiasRemision_idGuiaRemision` INT NOT NULL,
  PRIMARY KEY (`idDetalleGuia`),
  INDEX `fk_DetalleGuias_GuiasRemision1_idx` (`GuiasRemision_idGuiaRemision` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleGuias_GuiasRemision1`
    FOREIGN KEY (`GuiasRemision_idGuiaRemision`)
    REFERENCES `TOOLSRENTAL`.`GuiasRemision` (`idGuiaRemision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`ProductosHEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`ProductosHEM` (
  `idProdHEM` INT NOT NULL,
  `nomProdHEM` VARCHAR(45) NULL,
  `codProdHEM` VARCHAR(45) NULL,
  `descProdHEM` VARCHAR(45) NULL,
  `idCategoria` INT NULL,
  `stock` INT NULL,
  `precio` DECIMAL NULL,
  `idProv` INT NULL,
  `img` VARCHAR(45) NULL,
  `Orden_idOrden` INT NOT NULL,
  `Orden_Pedidos_idPedido` INT NOT NULL,
  `Orden_Pedidos_Clientes_idCliente` INT NOT NULL,
  `Categorias_idCategoria` INT NOT NULL,
  `DetalleGuias_idDetalleGuia` INT NOT NULL,
  PRIMARY KEY (`idProdHEM`, `Orden_idOrden`, `Orden_Pedidos_idPedido`, `Orden_Pedidos_Clientes_idCliente`, `Categorias_idCategoria`),
  INDEX `fk_ProductosHEM_Orden1_idx` (`Orden_idOrden` ASC, `Orden_Pedidos_idPedido` ASC, `Orden_Pedidos_Clientes_idCliente` ASC) VISIBLE,
  INDEX `fk_ProductosHEM_Categorias1_idx` (`Categorias_idCategoria` ASC) VISIBLE,
  INDEX `fk_ProductosHEM_DetalleGuias1_idx` (`DetalleGuias_idDetalleGuia` ASC) VISIBLE,
  CONSTRAINT `fk_ProductosHEM_Orden1`
    FOREIGN KEY (`Orden_idOrden` , `Orden_Pedidos_idPedido` , `Orden_Pedidos_Clientes_idCliente`)
    REFERENCES `TOOLSRENTAL`.`DetallePedidos` (`idDetPed` , `Pedidos_idPedido` , `Pedidos_Clientes_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosHEM_Categorias1`
    FOREIGN KEY (`Categorias_idCategoria`)
    REFERENCES `TOOLSRENTAL`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosHEM_DetalleGuias1`
    FOREIGN KEY (`DetalleGuias_idDetalleGuia`)
    REFERENCES `TOOLSRENTAL`.`DetalleGuias` (`idDetalleGuia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`Proveedores` (
  `idProveedor` INT NOT NULL,
  `nomProveedor` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `paginaWeb` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `comuna` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `altura` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `ProductosHEM_idProdHEM` INT NOT NULL,
  PRIMARY KEY (`idProveedor`, `ProductosHEM_idProdHEM`),
  INDEX `fk_Proveedores_ProductosHEM1_idx` (`ProductosHEM_idProdHEM` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedores_ProductosHEM1`
    FOREIGN KEY (`ProductosHEM_idProdHEM`)
    REFERENCES `TOOLSRENTAL`.`ProductosHEM` (`idProdHEM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`Email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`Email` (
  `idEmail` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idEmail`, `Clientes_idCliente`),
  INDEX `fk_Email_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Email_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `TOOLSRENTAL`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`Tel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`Tel` (
  `idTel` INT NOT NULL,
  `tlf` VARCHAR(45) NULL,
  `Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idTel`, `Clientes_idCliente`),
  INDEX `fk_Tel_Clientes_idx` (`Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Tel_Clientes`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `TOOLSRENTAL`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`TipoTlf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`TipoTlf` (
  `idTipoTlf` INT NOT NULL,
  `TipoTlf` VARCHAR(45) NULL,
  `Tel_idTel` INT NOT NULL,
  `Tel_Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idTipoTlf`, `Tel_idTel`, `Tel_Clientes_idCliente`),
  INDEX `fk_TipoTlf_Tel1_idx` (`Tel_idTel` ASC, `Tel_Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_TipoTlf_Tel1`
    FOREIGN KEY (`Tel_idTel` , `Tel_Clientes_idCliente`)
    REFERENCES `TOOLSRENTAL`.`Tel` (`idTel` , `Clientes_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`Contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`Contactos` (
  `idContacto` INT NOT NULL,
  `nomContacto` VARCHAR(45) NULL,
  `numCelular` VARCHAR(45) NULL,
  `Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idContacto`),
  INDEX `fk_Contactos_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Contactos_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `TOOLSRENTAL`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOOLSRENTAL`.`RegFiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TOOLSRENTAL`.`RegFiscal` (
  `idRegFiscal` INT NOT NULL,
  `RegFiscal` VARCHAR(45) NULL,
  `Clientes_idCliente` INT NOT NULL,
  `Proveedores_idProveedor` INT NOT NULL,
  `Proveedores_ProductosHEM_idProdHEM` INT NOT NULL,
  PRIMARY KEY (`idRegFiscal`, `Proveedores_idProveedor`, `Proveedores_ProductosHEM_idProdHEM`),
  INDEX `fk_RegFiscal_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  INDEX `fk_RegFiscal_Proveedores1_idx` (`Proveedores_idProveedor` ASC, `Proveedores_ProductosHEM_idProdHEM` ASC) VISIBLE,
  CONSTRAINT `fk_RegFiscal_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `TOOLSRENTAL`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegFiscal_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor` , `Proveedores_ProductosHEM_idProdHEM`)
    REFERENCES `TOOLSRENTAL`.`Proveedores` (`idProveedor` , `ProductosHEM_idProdHEM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
